// <auto-generated />
using CombatGameSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombatGameSite.Migrations
{
    [DbContext(typeof(CombatContext))]
    [Migration("20241120200936_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombatGameSite.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<double>("DefenseMultiplier")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 0,
                            Cost = 10,
                            DefenseMultiplier = 1.2,
                            Description = "A soothing wave of water heals the target.",
                            Name = "Healing Wave",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Attack = 20,
                            Cost = 15,
                            DefenseMultiplier = 1.0,
                            Description = "A blazing sphere of fire strikes the enemy.",
                            Name = "Fireball",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Attack = 0,
                            Cost = 12,
                            DefenseMultiplier = 1.5,
                            Description = "A swirling wind protects against attacks.",
                            Name = "Wind Barrier",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Attack = 25,
                            Cost = 18,
                            DefenseMultiplier = 1.0,
                            Description = "A fiery explosion dealing massive damage.",
                            Name = "Inferno Burst",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Attack = 0,
                            Cost = 8,
                            DefenseMultiplier = 1.1000000000000001,
                            Description = "A small burst of water to heal minor wounds.",
                            Name = "Aqua Surge",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Attack = 0,
                            Cost = 14,
                            DefenseMultiplier = 1.8,
                            Description = "Earth magic hardens the skin for defense.",
                            Name = "Stone Skin",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            Attack = 22,
                            Cost = 20,
                            DefenseMultiplier = 1.0,
                            Description = "A cutting wind attack that pierces defenses.",
                            Name = "Cyclone Slash",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Attack = 0,
                            Cost = 9,
                            DefenseMultiplier = 1.3999999999999999,
                            Description = "Encases the target in a veil of water for protection.",
                            Name = "Water Veil",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Attack = 0,
                            Cost = 11,
                            DefenseMultiplier = 1.3,
                            Description = "A gentle wind revitalizes the target.",
                            Name = "Breeze of Life",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Attack = 24,
                            Cost = 17,
                            DefenseMultiplier = 1.0,
                            Description = "An earth-shaking attack to crush enemies.",
                            Name = "Earthquake Smash",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            Attack = 0,
                            Cost = 16,
                            DefenseMultiplier = 1.6000000000000001,
                            Description = "A shield of fire reduces incoming damage.",
                            Name = "Flame Ward",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Attack = 0,
                            Cost = 13,
                            DefenseMultiplier = 1.2,
                            Description = "The power of earth heals the target slowly.",
                            Name = "Earthen Rejuvenation",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Attack = 26,
                            Cost = 19,
                            DefenseMultiplier = 1.0,
                            Description = "A wave crashes on the enemy for damage.",
                            Name = "Tidal Crush",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Attack = 0,
                            Cost = 10,
                            DefenseMultiplier = 1.7,
                            Description = "A massive wind barrier blocks attacks.",
                            Name = "Wind Fortress",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Attack = 0,
                            Cost = 12,
                            DefenseMultiplier = 1.1000000000000001,
                            Description = "A fiery warmth restores the target's health.",
                            Name = "Flare Heal",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Attack = 28,
                            Cost = 21,
                            DefenseMultiplier = 1.0,
                            Description = "Rocks pummel the enemy, causing severe damage.",
                            Name = "Landslide Strike",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Attack = 0,
                            Cost = 15,
                            DefenseMultiplier = 1.5,
                            Description = "A shield of water dampens damage.",
                            Name = "Aqua Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Attack = 0,
                            Cost = 10,
                            DefenseMultiplier = 1.1000000000000001,
                            Description = "A calming wind that heals minor injuries.",
                            Name = "Soothing Breeze",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            Attack = 30,
                            Cost = 22,
                            DefenseMultiplier = 1.0,
                            Description = "A sword engulfed in fire slashes the enemy.",
                            Name = "Flaming Blade",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Attack = 0,
                            Cost = 13,
                            DefenseMultiplier = 1.8999999999999999,
                            Description = "A massive wall of earth defends against attacks.",
                            Name = "Rock Wall",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            Attack = 0,
                            Cost = 14,
                            DefenseMultiplier = 1.2,
                            Description = "Tiny stones infused with healing power.",
                            Name = "Healing Pebbles",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 22,
                            Attack = 32,
                            Cost = 25,
                            DefenseMultiplier = 1.0,
                            Description = "A sharp blade of water cuts through the enemy.",
                            Name = "Aqua Slash",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            Attack = 0,
                            Cost = 18,
                            DefenseMultiplier = 1.7,
                            Description = "A burning shield reduces damage taken.",
                            Name = "Blazing Barrier",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            Attack = 0,
                            Cost = 12,
                            DefenseMultiplier = 1.2,
                            Description = "A soft breeze heals and rejuvenates.",
                            Name = "Whispering Wind",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 25,
                            Attack = 33,
                            Cost = 23,
                            DefenseMultiplier = 1.0,
                            Description = "A ferocious wind slashes the enemy.",
                            Name = "Tempest Fang",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Attack = 0,
                            Cost = 15,
                            DefenseMultiplier = 1.6000000000000001,
                            Description = "A watery shield protects the user.",
                            Name = "Ocean Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            Attack = 0,
                            Cost = 10,
                            DefenseMultiplier = 1.1000000000000001,
                            Description = "A quick burst of fire heals the target.",
                            Name = "Flame Pulse",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 28,
                            Attack = 34,
                            Cost = 24,
                            DefenseMultiplier = 1.0,
                            Description = "A giant boulder crushes the opponent.",
                            Name = "Boulder Bash",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 29,
                            Attack = 0,
                            Cost = 19,
                            DefenseMultiplier = 1.8,
                            Description = "A rotating wind reduces damage.",
                            Name = "Cyclone Guard",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Attack = 0,
                            Cost = 14,
                            DefenseMultiplier = 1.3,
                            Description = "A gentle rain restores the target's health.",
                            Name = "Rain of Healing",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            Attack = 35,
                            Cost = 26,
                            DefenseMultiplier = 1.0,
                            Description = "A fiery wave burns all in its path.",
                            Name = "Flame Surge",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 32,
                            Attack = 0,
                            Cost = 20,
                            DefenseMultiplier = 1.8,
                            Description = "Earth barriers defend against attacks.",
                            Name = "Rock Shield",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 33,
                            Attack = 0,
                            Cost = 13,
                            DefenseMultiplier = 1.3,
                            Description = "A rejuvenating wind heals all nearby allies.",
                            Name = "Winds of Renewal",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Attack = 36,
                            Cost = 27,
                            DefenseMultiplier = 1.0,
                            Description = "A torrent of water smashes the enemy.",
                            Name = "Ocean Blast",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            Attack = 0,
                            Cost = 18,
                            DefenseMultiplier = 1.7,
                            Description = "A barrier of molten fire absorbs damage.",
                            Name = "Lava Shield",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 36,
                            Attack = 0,
                            Cost = 16,
                            DefenseMultiplier = 1.2,
                            Description = "The earth's power restores health gradually.",
                            Name = "Earth Embrace",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 37,
                            Attack = 37,
                            Cost = 29,
                            DefenseMultiplier = 1.0,
                            Description = "A devastating lightning-charged wind attack.",
                            Name = "Storm Strike",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Attack = 0,
                            Cost = 20,
                            DefenseMultiplier = 1.6000000000000001,
                            Description = "Encases the user in a protective bubble.",
                            Name = "Bubble Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            Attack = 0,
                            Cost = 12,
                            DefenseMultiplier = 1.1000000000000001,
                            Description = "A healing ember that soothes wounds.",
                            Name = "Ember Heal",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("CombatGameSite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "alice",
                            Password = "password",
                            Tagline = "Hello, world!"
                        },
                        new
                        {
                            Id = 2,
                            Name = "bob",
                            Password = "password",
                            Tagline = "Catchphrase."
                        },
                        new
                        {
                            Id = 3,
                            Name = "charlie",
                            Password = "password",
                            Tagline = "Super smashing success."
                        },
                        new
                        {
                            Id = 4,
                            Name = "dave",
                            Password = "password",
                            Tagline = "Game on."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
