// <auto-generated />
using System;
using CombatGameSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombatGameSite.Migrations
{
    [DbContext(typeof(CombatContext))]
    [Migration("20241202220023_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombatGameSite.Models.Character", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Health")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillPrimaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SkillSecondaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SkillTertiaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillPrimaryId");

                    b.HasIndex("SkillSecondaryId");

                    b.HasIndex("SkillTertiaryId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Health = 100,
                            Name = "Aqua Warrior",
                            SkillPrimaryId = "A1",
                            SkillSecondaryId = "A2",
                            SkillTertiaryId = "H1",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Health = 100,
                            Name = "Flame Destroyer",
                            SkillPrimaryId = "A3",
                            SkillSecondaryId = "A4",
                            SkillTertiaryId = "H1",
                            Species = "Elf",
                            TypeId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Health = 100,
                            Name = "Wind Ninja",
                            SkillPrimaryId = "A5",
                            SkillSecondaryId = "A6",
                            SkillTertiaryId = "H1",
                            Species = "Dwarf",
                            TypeId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Health = 100,
                            Name = "Earth Titan",
                            SkillPrimaryId = "A7",
                            SkillSecondaryId = "A8",
                            SkillTertiaryId = "H1",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Health = 100,
                            Name = "Water Sage",
                            SkillPrimaryId = "A9",
                            SkillSecondaryId = "A10",
                            SkillTertiaryId = "H1",
                            Species = "Elf",
                            TypeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Health = 100,
                            Name = "Fire Knight",
                            SkillPrimaryId = "A11",
                            SkillSecondaryId = "A12",
                            SkillTertiaryId = "H1",
                            Species = "Dwarf",
                            TypeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Health = 100,
                            Name = "Wind Shaman",
                            SkillPrimaryId = "A13",
                            SkillSecondaryId = "A13",
                            SkillTertiaryId = "H1",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Health = 100,
                            Name = "Earth Wizard",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H1",
                            Species = "Elf",
                            TypeId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Health = 100,
                            Name = "Water Spirit",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H1",
                            Species = "Dwarf",
                            TypeId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Health = 100,
                            Name = "Flame Phoenix",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H1",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Health = 100,
                            Name = "Wind Warrior",
                            SkillPrimaryId = "A1",
                            SkillSecondaryId = "A2",
                            SkillTertiaryId = "H2",
                            Species = "Elf",
                            TypeId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Health = 100,
                            Name = "Fire Sorcerer",
                            SkillPrimaryId = "A3",
                            SkillSecondaryId = "A4",
                            SkillTertiaryId = "H2",
                            Species = "Dwarf",
                            TypeId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            Health = 100,
                            Name = "Wind Elf",
                            SkillPrimaryId = "A5",
                            SkillSecondaryId = "A6",
                            SkillTertiaryId = "H2",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Health = 100,
                            Name = "Earth Golem",
                            SkillPrimaryId = "A7",
                            SkillSecondaryId = "A8",
                            SkillTertiaryId = "H2",
                            Species = "Elf",
                            TypeId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Health = 100,
                            Name = "Water Knight",
                            SkillPrimaryId = "A9",
                            SkillSecondaryId = "A10",
                            SkillTertiaryId = "H2",
                            Species = "Dwarf",
                            TypeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            Health = 100,
                            Name = "Fire Wizard",
                            SkillPrimaryId = "A11",
                            SkillSecondaryId = "A12",
                            SkillTertiaryId = "H2",
                            Species = "Human",
                            TypeId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Health = 100,
                            Name = "Wind Shaman",
                            SkillPrimaryId = "A13",
                            SkillSecondaryId = "A13",
                            SkillTertiaryId = "H2",
                            Species = "Elf",
                            TypeId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Health = 100,
                            Name = "Water Guardian",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H2",
                            Species = "Dwarf",
                            TypeId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Health = 100,
                            Name = "Flame Demon",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H2",
                            Species = "Human",
                            TypeId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            Health = 100,
                            Name = "Wind Demon",
                            SkillPrimaryId = "H1",
                            SkillSecondaryId = "H1",
                            SkillTertiaryId = "H2",
                            Species = "Elf",
                            TypeId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            Health = 100,
                            Name = "Water Monk",
                            SkillPrimaryId = "A1",
                            SkillSecondaryId = "A2",
                            SkillTertiaryId = "H3",
                            Species = "Dwarf",
                            TypeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Health = 100,
                            Name = "Fire Samurai",
                            SkillPrimaryId = "A3",
                            SkillSecondaryId = "A4",
                            SkillTertiaryId = "H3",
                            Species = "Human",
                            TypeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Health = 100,
                            Name = "Wind Warrior",
                            SkillPrimaryId = "A5",
                            SkillSecondaryId = "A6",
                            SkillTertiaryId = "H3",
                            Species = "Elf",
                            TypeId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            Health = 100,
                            Name = "Earth Beast",
                            SkillPrimaryId = "A7",
                            SkillSecondaryId = "A8",
                            SkillTertiaryId = "H3",
                            Species = "Dwarf",
                            TypeId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            Health = 100,
                            Name = "Water Sorceress",
                            SkillPrimaryId = "A9",
                            SkillSecondaryId = "A10",
                            SkillTertiaryId = "H3",
                            Species = "Human",
                            TypeId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CombatGameSite.Models.Skill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Attack")
                        .HasColumnType("int");

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = "H1",
                            Attack = 0,
                            Cost = 10,
                            Description = "A soothing wave of water heals the target.",
                            Name = "Healing Wave",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "A1",
                            Attack = 20,
                            Cost = 15,
                            Description = "A blazing sphere of fire strikes the enemy.",
                            Name = "Fireball",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "D1",
                            Attack = 0,
                            Cost = 12,
                            Description = "A swirling wind protects against attacks.",
                            Name = "Wind Barrier",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "A2",
                            Attack = 25,
                            Cost = 18,
                            Description = "A fiery explosion dealing massive damage.",
                            Name = "Inferno Burst",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "H2",
                            Attack = 0,
                            Cost = 8,
                            Description = "A small burst of water to heal minor wounds.",
                            Name = "Aqua Surge",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "D2",
                            Attack = 0,
                            Cost = 14,
                            Description = "Earth magic hardens the skin for defense.",
                            Name = "Stone Skin",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "A3",
                            Attack = 22,
                            Cost = 20,
                            Description = "A cutting wind attack that pierces defenses.",
                            Name = "Cyclone Slash",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "D3",
                            Attack = 0,
                            Cost = 9,
                            Description = "Encases the target in a veil of water for protection.",
                            Name = "Water Veil",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "H3",
                            Attack = 0,
                            Cost = 11,
                            Description = "A gentle wind revitalizes the target.",
                            Name = "Breeze of Life",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "A4",
                            Attack = 24,
                            Cost = 17,
                            Description = "An earth-shaking attack to crush enemies.",
                            Name = "Earthquake Smash",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "D4",
                            Attack = 0,
                            Cost = 16,
                            Description = "A shield of fire reduces incoming damage.",
                            Name = "Flame Ward",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "H4",
                            Attack = 0,
                            Cost = 13,
                            Description = "The power of earth heals the target slowly.",
                            Name = "Earthen Rejuvenation",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "A5",
                            Attack = 26,
                            Cost = 19,
                            Description = "A wave crashes on the enemy for damage.",
                            Name = "Tidal Crush",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "D5",
                            Attack = 0,
                            Cost = 10,
                            Description = "A massive wind barrier blocks attacks.",
                            Name = "Wind Fortress",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "H5",
                            Attack = 0,
                            Cost = 12,
                            Description = "A fiery warmth restores the target's health.",
                            Name = "Flare Heal",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "A6",
                            Attack = 28,
                            Cost = 21,
                            Description = "Rocks pummel the enemy, causing severe damage.",
                            Name = "Landslide Strike",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "D6",
                            Attack = 0,
                            Cost = 15,
                            Description = "A shield of water dampens damage.",
                            Name = "Aqua Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "H6",
                            Attack = 0,
                            Cost = 10,
                            Description = "A calming wind that heals minor injuries.",
                            Name = "Soothing Breeze",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "A7",
                            Attack = 30,
                            Cost = 22,
                            Description = "A sword engulfed in fire slashes the enemy.",
                            Name = "Flaming Blade",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "D7",
                            Attack = 0,
                            Cost = 13,
                            Description = "A massive wall of earth defends against attacks.",
                            Name = "Rock Wall",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "H7",
                            Attack = 0,
                            Cost = 14,
                            Description = "Tiny stones infused with healing power.",
                            Name = "Healing Pebbles",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "A8",
                            Attack = 32,
                            Cost = 25,
                            Description = "A sharp blade of water cuts through the enemy.",
                            Name = "Aqua Slash",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "D8",
                            Attack = 0,
                            Cost = 18,
                            Description = "A burning shield reduces damage taken.",
                            Name = "Blazing Barrier",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "H8",
                            Attack = 0,
                            Cost = 12,
                            Description = "A soft breeze heals and rejuvenates.",
                            Name = "Whispering Wind",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "A9",
                            Attack = 33,
                            Cost = 23,
                            Description = "A ferocious wind slashes the enemy.",
                            Name = "Tempest Fang",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "D9",
                            Attack = 0,
                            Cost = 15,
                            Description = "A watery shield protects the user.",
                            Name = "Ocean Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "H9",
                            Attack = 0,
                            Cost = 10,
                            Description = "A quick burst of fire heals the target.",
                            Name = "Flame Pulse",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "A10",
                            Attack = 34,
                            Cost = 24,
                            Description = "A giant boulder crushes the opponent.",
                            Name = "Boulder Bash",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "D10",
                            Attack = 0,
                            Cost = 19,
                            Description = "A rotating wind reduces damage.",
                            Name = "Cyclone Guard",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "H10",
                            Attack = 0,
                            Cost = 14,
                            Description = "A gentle rain restores the target's health.",
                            Name = "Rain of Healing",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "A11",
                            Attack = 35,
                            Cost = 26,
                            Description = "A fiery wave burns all in its path.",
                            Name = "Flame Surge",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "D11",
                            Attack = 0,
                            Cost = 20,
                            Description = "Earth barriers defend against attacks.",
                            Name = "Rock Shield",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "H11",
                            Attack = 0,
                            Cost = 13,
                            Description = "A rejuvenating wind heals all nearby allies.",
                            Name = "Winds of Renewal",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "A12",
                            Attack = 36,
                            Cost = 27,
                            Description = "A torrent of water smashes the enemy.",
                            Name = "Ocean Blast",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "D12",
                            Attack = 0,
                            Cost = 18,
                            Description = "A barrier of molten fire absorbs damage.",
                            Name = "Lava Shield",
                            TypeId = 2
                        },
                        new
                        {
                            Id = "H12",
                            Attack = 0,
                            Cost = 16,
                            Description = "The earth's power restores health gradually.",
                            Name = "Earth Embrace",
                            TypeId = 4
                        },
                        new
                        {
                            Id = "A13",
                            Attack = 37,
                            Cost = 29,
                            Description = "A devastating lightning-charged wind attack.",
                            Name = "Storm Strike",
                            TypeId = 3
                        },
                        new
                        {
                            Id = "D13",
                            Attack = 0,
                            Cost = 20,
                            Description = "Encases the user in a protective bubble.",
                            Name = "Bubble Shield",
                            TypeId = 1
                        },
                        new
                        {
                            Id = "H13",
                            Attack = 0,
                            Cost = 12,
                            Description = "A healing ember that soothes wounds.",
                            Name = "Ember Heal",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("CombatGameSite.Models.Team", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Character1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Character2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Character3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Character4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Character5Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Character1Id");

                    b.HasIndex("Character2Id");

                    b.HasIndex("Character3Id");

                    b.HasIndex("Character4Id");

                    b.HasIndex("Character5Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Character1Id = 1,
                            Character2Id = 5,
                            Character3Id = 9,
                            Character4Id = 13,
                            Character5Id = 17,
                            Name = "Aqua Defenders",
                            Score = 150,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Character1Id = 1,
                            Character2Id = 5,
                            Character3Id = 9,
                            Character4Id = 13,
                            Character5Id = 21,
                            Name = "Tidal Guardians",
                            Score = 140,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Character1Id = 9,
                            Character2Id = 13,
                            Character3Id = 17,
                            Character4Id = 21,
                            Character5Id = 25,
                            Name = "Water Warriors",
                            Score = 130,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Character1Id = 2,
                            Character2Id = 6,
                            Character3Id = 10,
                            Character4Id = 14,
                            Character5Id = 18,
                            Name = "Blazing Firestorm",
                            Score = 160,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Character1Id = 2,
                            Character2Id = 6,
                            Character3Id = 10,
                            Character4Id = 14,
                            Character5Id = 22,
                            Name = "Inferno Knights",
                            Score = 140,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Character1Id = 6,
                            Character2Id = 10,
                            Character3Id = 14,
                            Character4Id = 18,
                            Character5Id = 22,
                            Name = "Fire Warriors",
                            Score = 135,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Character1Id = 3,
                            Character2Id = 7,
                            Character3Id = 11,
                            Character4Id = 15,
                            Character5Id = 19,
                            Name = "Wind Strikers",
                            Score = 150,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Character1Id = 3,
                            Character2Id = 7,
                            Character3Id = 11,
                            Character4Id = 15,
                            Character5Id = 23,
                            Name = "Zephyr Champions",
                            Score = 145,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Character1Id = 7,
                            Character2Id = 11,
                            Character3Id = 15,
                            Character4Id = 19,
                            Character5Id = 23,
                            Name = "Sky Protectors",
                            Score = 140,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Character1Id = 4,
                            Character2Id = 8,
                            Character3Id = 12,
                            Character4Id = 16,
                            Character5Id = 20,
                            Name = "Earth Titans",
                            Score = 160,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Character1Id = 4,
                            Character2Id = 8,
                            Character3Id = 12,
                            Character4Id = 16,
                            Character5Id = 24,
                            Name = "Rock Guardians",
                            Score = 150,
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            Character1Id = 8,
                            Character2Id = 12,
                            Character3Id = 16,
                            Character4Id = 20,
                            Character5Id = 24,
                            Name = "Stone Warriors",
                            Score = 140,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("CombatGameSite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FavoriteBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteBook = "Alice in Wonderland",
                            FavoriteGame = "Kingdom Hearts 2",
                            FavoriteMovie = "The Lion King",
                            Name = "alice",
                            Password = "password",
                            Tagline = "Hello, world!"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteBook = "The Unofficial Guide to Fortnite",
                            FavoriteGame = "Fortnite",
                            FavoriteMovie = "Fortnite: The Movie",
                            Name = "bob",
                            Password = "password",
                            Tagline = "Catchphrase."
                        },
                        new
                        {
                            Id = 3,
                            FavoriteBook = "Jumpmap",
                            FavoriteGame = "Super Mario Bros",
                            FavoriteMovie = "Terminator",
                            Name = "charlie",
                            Password = "password",
                            Tagline = "Super smashing success."
                        },
                        new
                        {
                            Id = 4,
                            FavoriteBook = "x86 For Professionals",
                            FavoriteGame = "Roller Coaster Tycoon",
                            FavoriteMovie = "A Student Film",
                            Name = "dave",
                            Password = "password",
                            Tagline = "It's not broke. You're just bad."
                        });
                });

            modelBuilder.Entity("CombatGameSite.Models.Character", b =>
                {
                    b.HasOne("CombatGameSite.Models.Skill", "SkillPrimary")
                        .WithMany()
                        .HasForeignKey("SkillPrimaryId");

                    b.HasOne("CombatGameSite.Models.Skill", "SkillSecondary")
                        .WithMany()
                        .HasForeignKey("SkillSecondaryId");

                    b.HasOne("CombatGameSite.Models.Skill", "SkillTertiary")
                        .WithMany()
                        .HasForeignKey("SkillTertiaryId");

                    b.HasOne("CombatGameSite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SkillPrimary");

                    b.Navigation("SkillSecondary");

                    b.Navigation("SkillTertiary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CombatGameSite.Models.Team", b =>
                {
                    b.HasOne("CombatGameSite.Models.Character", "Character1")
                        .WithMany()
                        .HasForeignKey("Character1Id");

                    b.HasOne("CombatGameSite.Models.Character", "Character2")
                        .WithMany()
                        .HasForeignKey("Character2Id");

                    b.HasOne("CombatGameSite.Models.Character", "Character3")
                        .WithMany()
                        .HasForeignKey("Character3Id");

                    b.HasOne("CombatGameSite.Models.Character", "Character4")
                        .WithMany()
                        .HasForeignKey("Character4Id");

                    b.HasOne("CombatGameSite.Models.Character", "Character5")
                        .WithMany()
                        .HasForeignKey("Character5Id");

                    b.HasOne("CombatGameSite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Character1");

                    b.Navigation("Character2");

                    b.Navigation("Character3");

                    b.Navigation("Character4");

                    b.Navigation("Character5");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
